### ISSUE TITLE
Can't find algorithm description

### ISSUE THREAD

**Issue by electroniceel** [Orolia2s/disciplining-minipod#48]
Hi, 

I would like to learn about the details of the algorithm used.

There is a link to https://bitbucket.org/spectracom/minipod/src/master/ in the readme, but unfortunately it now leads to a 404. I wasn't able to find it anywhere else.

Do you happen to have a copy of the algorithm description you could upload or send me?

Thank you.

**Comment by agagniere** [comment]
Hi,

I'm afraid there isn't much documentation outside of the code itself.
